export const ADD_INGREDIENT = 'ADD INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE INGREDIENT';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAIL = 'SET_INGREDIENTS_FAIL';
